# Generated by Django 5.1.6 on 2025-03-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='imageapp_user',
        ),
    ]
